ALTER TABLE CUSTOMER_REGISTRY 
ALTER COLUMN EMAIL SET NOT NULL;

ALTER TABLE CUSTOMER_ASSIGNMENT
ALTER COLUMN STARTDATE SET NOT NULL;

ALTER TABLE CUSTOMER_ASSIGNMENT
ALTER COLUMN FK_CUSTOMER_REGISTRY SET NOT NULL;

ALTER TABLE PROJECT_ASSIGNMENT
ALTER COLUMN STARTDATE SET NOT NULL;

ALTER TABLE PROJECT_ASSIGNMENT
ALTER COLUMN FK_PROJECT SET NOT NULL;

ALTER TABLE CONTRIBUTOR
ALTER COLUMN EMAIL SET NOT NULL;

ALTER TABLE CONTRIBUTOR
ALTER COLUMN USERID SET NOT NULL;

ALTER TABLE UNASSIGNED_CONTRIBUTOR
ALTER COLUMN EMAIL SET NOT NULL;

ALTER TABLE DEPARTMENT
ALTER COLUMN ACTIVITY SET NOT NULL;

ALTER TABLE DEPARTMENT
ALTER COLUMN OFFICE SET NOT NULL;

ALTER TABLE DEPARTMENT
ALTER COLUMN DIVISION SET NOT NULL;

ALTER TABLE DEPARTMENT
ALTER COLUMN SECTION SET NOT NULL;

ALTER TABLE SOURCES
ALTER COLUMN CODE SET NOT NULL;

ALTER TABLE SOURCES
ALTER COLUMN NAME SET NOT NULL;

ALTER TABLE REPOSITORY
ALTER COLUMN NAME SET NOT NULL;

ALTER TABLE REPOSITORY
ALTER COLUMN FK_PROJECT SET NOT NULL;

ALTER TABLE REVISIONS
ALTER COLUMN SHA SET NOT NULL;

ALTER TABLE REVISIONS 
ALTER COLUMN FK_REPOSITORY SET NOT NULL;

ALTER TABLE REVISIONS
ALTER COLUMN TIME SET NOT NULL;

ALTER TABLE MODIFICATION 
ALTER COLUMN FK_REVISION SET NOT NULL;

ALTER TABLE MODIFICATION 
ALTER COLUMN BRANCH SET NOT NULL;

ALTER TABLE MODIFICATION 
ALTER COLUMN RAW SET NOT NULL;

ALTER TABLE MODIFICATION 
ALTER COLUMN PATHNAME SET NOT NULL;

INSERT INTO PATCHLEVEL("PATCH") VALUES('V3');