ALTER TABLE TRANSFERS
ADD COLUMN OFFSET0 INTEGER;

CREATE TABLE STAGE_CONTRIBUTOR (
    ID INTEGER PRIMARY KEY,
    EMAIL TEXT NOT NULL,
    USERID TEXT,
    COLORID INTEGER
);

CREATE UNIQUE INDEX IDX_STAGE_CONTRIBUTOR_U ON STAGE_CONTRIBUTOR(EMAIL);

CREATE TABLE STAGE_REVISIONS (
    ID INTEGER PRIMARY KEY,
    SHA TEXT NOT NULL,
    TIME INTEGER NOT NULL,
    MESSAGE TEXT,
    FK_REPOSITORY INTEGER,
    FK_CONTRIBUTOR INTEGER,
    FORKED INTEGER,
    COLORID INTEGER,
    FOREIGN KEY(FK_CONTRIBUTOR) REFERENCES stage_contributor(id),
    FOREIGN KEY(FK_REPOSITORY) REFERENCES repository(id)
);

CREATE UNIQUE INDEX IDX_STAGE_REVISIONS_U ON STAGE_REVISIONS(SHA, FK_REPOSITORY, TIME);
CREATE INDEX STAGE_REVISIONS_TIME ON STAGE_REVISIONS(TIME, FORKED);

CREATE TABLE STAGE_MODIFICATION (
    ID INTEGER PRIMARY KEY,
    BRANCH TEXT NOT NULL,
    PATHNAME TEXT NOT NULL,
    INSERTIONS INTEGER,
    DELETIONS INTEGER,
    RAW INTEGER NOT NULL,
    IS_BIN INTEGER,
    EXTENSION TEXT,
    FK_REVISION INTEGER,
    COLORID INTEGER,
    FOREIGN KEY(FK_REVISION) REFERENCES stage_revisions(id)
);

CREATE UNIQUE INDEX IDX_STAGE_MODIFICATION_U ON STAGE_MODIFICATION(FK_REVISION, BRANCH, RAW, PATHNAME);

CREATE TABLE STAGE_TRANSFERS(
    TIME TEXT,
    ELAPSED INTEGER,
    FK_REPOSITORY INTEGER,
    BRANCH TEXT,
    COUNTER INTEGER,
    CHANGES INTEGER,
    NOTES TEXT,
    COLORID INTEGER,
    OFFSET0 INTEGER,
    FOREIGN KEY(FK_REPOSITORY) REFERENCES repository(id)
);

INSERT INTO PATCHLEVEL("PATCH") VALUES('V4');